### PR TITLE
Convert to generic promise plugin (fixes #2)

### LINKED ISSUE #2: More promise related rules
Hey @jden would you have any interest in adding additional promise related rules such as the one proposed here? https://github.com/eslint/eslint/issues/1092

I'd be happy to write the code for it.

### PR DESCRIPTION
**Pull request by xjamundx**
Hey, here's one idea for re-imagining this into a more generic rule. I'm not a promise expert, but I was eager to work on these. If you're not okay with this I can do it as my own fork or whatever, but if you want to take these changes and make them part of your plugin that's sweet. 
- [x] Added `always-catch` rule
- [x] Added `always-return` rule
- [x] Renamed `promiseparams` rule to `param-names`
- [x] Renamed the rule to `eslint-plugin-promise`

### CODE REVIEW

**Comment by junosuarez** [comment]
The name is pretty specific, and I don't want to confuse issues with the npm package name (I'm currently using it in my build process on a project at work). I think the better direction is to create the new more generic promise rules package in a new repo. If you'd like, I'm happy to place a deprecation / forwarding warning in the readme of this repo and republish that as a patch version on npm.

**Comment by xjamundx** [comment]
Great, I'll go ahead and start a new thing here https://github.com/xjamundx/eslint-plugin-promise/

Do you want to be an owner on the project as well?

**Comment by junosuarez** [comment]
I don't think I'll have time to be actively contributing to it, so that's not necessary. Thank you, though, for making this! Very useful.

**Comment by xjamundx** [comment]
Thanks for your code @jden !

**Comment by junosuarez** [comment]
No problem, open source is great :) I've added a deprecation / forwarding note on the readme for this repo.

**Pull request closed without merging**
